spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      lettuce:
        pool:
          max-active: 8
          max-idle: 0
          min-idle: 0
          max-wait: 100ms
  mail:
    host: smtp.163.com
    port: 465
    username: cutejiuge@163.com
    password: QN2eC355YfhAwWBC
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: jakarta.net.ssl.SSLSocketFactory
          starttls:
            enable: true
    protocol: smtps

mybatis-plus:
  type-aliases-package: com.easy_pan.back
  mapper-locations: classpath*:/mapper/**/*.xml
