/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.easy_pan.account;

import jakarta.annotation.Generated;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2025-06-02")
public class UserRegisterRequest implements org.apache.thrift.TBase<UserRegisterRequest, UserRegisterRequest._Fields>, java.io.Serializable, Cloneable, Comparable<UserRegisterRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserRegisterRequest");

  private static final org.apache.thrift.protocol.TField EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("email", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NICK_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("nickName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("password", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IMG_CHECK_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("imgCheckCode", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField EMAIL_VERIFY_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("emailVerifyCode", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField BASE_FIELD_DESC = new org.apache.thrift.protocol.TField("base", org.apache.thrift.protocol.TType.STRUCT, (short)255);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserRegisterRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserRegisterRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String email; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String nickName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String password; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String imgCheckCode; // required
  public long emailVerifyCode; // required
  public @org.apache.thrift.annotation.Nullable com.cutejiuge.base.Base base; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EMAIL((short)1, "email"),
    NICK_NAME((short)2, "nickName"),
    PASSWORD((short)3, "password"),
    IMG_CHECK_CODE((short)4, "imgCheckCode"),
    EMAIL_VERIFY_CODE((short)5, "emailVerifyCode"),
    BASE((short)255, "base");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EMAIL
          return EMAIL;
        case 2: // NICK_NAME
          return NICK_NAME;
        case 3: // PASSWORD
          return PASSWORD;
        case 4: // IMG_CHECK_CODE
          return IMG_CHECK_CODE;
        case 5: // EMAIL_VERIFY_CODE
          return EMAIL_VERIFY_CODE;
        case 255: // BASE
          return BASE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EMAILVERIFYCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.BASE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EMAIL, new org.apache.thrift.meta_data.FieldMetaData("email", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NICK_NAME, new org.apache.thrift.meta_data.FieldMetaData("nickName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("password", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMG_CHECK_CODE, new org.apache.thrift.meta_data.FieldMetaData("imgCheckCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMAIL_VERIFY_CODE, new org.apache.thrift.meta_data.FieldMetaData("emailVerifyCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.BASE, new org.apache.thrift.meta_data.FieldMetaData("base", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.cutejiuge.base.Base.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserRegisterRequest.class, metaDataMap);
  }

  public UserRegisterRequest() {
  }

  public UserRegisterRequest(
    java.lang.String email,
    java.lang.String nickName,
    java.lang.String password,
    java.lang.String imgCheckCode,
    long emailVerifyCode)
  {
    this();
    this.email = email;
    this.nickName = nickName;
    this.password = password;
    this.imgCheckCode = imgCheckCode;
    this.emailVerifyCode = emailVerifyCode;
    setEmailVerifyCodeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserRegisterRequest(UserRegisterRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetEmail()) {
      this.email = other.email;
    }
    if (other.isSetNickName()) {
      this.nickName = other.nickName;
    }
    if (other.isSetPassword()) {
      this.password = other.password;
    }
    if (other.isSetImgCheckCode()) {
      this.imgCheckCode = other.imgCheckCode;
    }
    this.emailVerifyCode = other.emailVerifyCode;
    if (other.isSetBase()) {
      this.base = new com.cutejiuge.base.Base(other.base);
    }
  }

  @Override
  public UserRegisterRequest deepCopy() {
    return new UserRegisterRequest(this);
  }

  @Override
  public void clear() {
    this.email = null;
    this.nickName = null;
    this.password = null;
    this.imgCheckCode = null;
    setEmailVerifyCodeIsSet(false);
    this.emailVerifyCode = 0;
    this.base = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEmail() {
    return this.email;
  }

  public UserRegisterRequest setEmail(@org.apache.thrift.annotation.Nullable java.lang.String email) {
    this.email = email;
    return this;
  }

  public void unsetEmail() {
    this.email = null;
  }

  /** Returns true if field email is set (has been assigned a value) and false otherwise */
  public boolean isSetEmail() {
    return this.email != null;
  }

  public void setEmailIsSet(boolean value) {
    if (!value) {
      this.email = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNickName() {
    return this.nickName;
  }

  public UserRegisterRequest setNickName(@org.apache.thrift.annotation.Nullable java.lang.String nickName) {
    this.nickName = nickName;
    return this;
  }

  public void unsetNickName() {
    this.nickName = null;
  }

  /** Returns true if field nickName is set (has been assigned a value) and false otherwise */
  public boolean isSetNickName() {
    return this.nickName != null;
  }

  public void setNickNameIsSet(boolean value) {
    if (!value) {
      this.nickName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPassword() {
    return this.password;
  }

  public UserRegisterRequest setPassword(@org.apache.thrift.annotation.Nullable java.lang.String password) {
    this.password = password;
    return this;
  }

  public void unsetPassword() {
    this.password = null;
  }

  /** Returns true if field password is set (has been assigned a value) and false otherwise */
  public boolean isSetPassword() {
    return this.password != null;
  }

  public void setPasswordIsSet(boolean value) {
    if (!value) {
      this.password = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getImgCheckCode() {
    return this.imgCheckCode;
  }

  public UserRegisterRequest setImgCheckCode(@org.apache.thrift.annotation.Nullable java.lang.String imgCheckCode) {
    this.imgCheckCode = imgCheckCode;
    return this;
  }

  public void unsetImgCheckCode() {
    this.imgCheckCode = null;
  }

  /** Returns true if field imgCheckCode is set (has been assigned a value) and false otherwise */
  public boolean isSetImgCheckCode() {
    return this.imgCheckCode != null;
  }

  public void setImgCheckCodeIsSet(boolean value) {
    if (!value) {
      this.imgCheckCode = null;
    }
  }

  public long getEmailVerifyCode() {
    return this.emailVerifyCode;
  }

  public UserRegisterRequest setEmailVerifyCode(long emailVerifyCode) {
    this.emailVerifyCode = emailVerifyCode;
    setEmailVerifyCodeIsSet(true);
    return this;
  }

  public void unsetEmailVerifyCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EMAILVERIFYCODE_ISSET_ID);
  }

  /** Returns true if field emailVerifyCode is set (has been assigned a value) and false otherwise */
  public boolean isSetEmailVerifyCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EMAILVERIFYCODE_ISSET_ID);
  }

  public void setEmailVerifyCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EMAILVERIFYCODE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public com.cutejiuge.base.Base getBase() {
    return this.base;
  }

  public UserRegisterRequest setBase(@org.apache.thrift.annotation.Nullable com.cutejiuge.base.Base base) {
    this.base = base;
    return this;
  }

  public void unsetBase() {
    this.base = null;
  }

  /** Returns true if field base is set (has been assigned a value) and false otherwise */
  public boolean isSetBase() {
    return this.base != null;
  }

  public void setBaseIsSet(boolean value) {
    if (!value) {
      this.base = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case EMAIL:
      if (value == null) {
        unsetEmail();
      } else {
        setEmail((java.lang.String)value);
      }
      break;

    case NICK_NAME:
      if (value == null) {
        unsetNickName();
      } else {
        setNickName((java.lang.String)value);
      }
      break;

    case PASSWORD:
      if (value == null) {
        unsetPassword();
      } else {
        setPassword((java.lang.String)value);
      }
      break;

    case IMG_CHECK_CODE:
      if (value == null) {
        unsetImgCheckCode();
      } else {
        setImgCheckCode((java.lang.String)value);
      }
      break;

    case EMAIL_VERIFY_CODE:
      if (value == null) {
        unsetEmailVerifyCode();
      } else {
        setEmailVerifyCode((java.lang.Long)value);
      }
      break;

    case BASE:
      if (value == null) {
        unsetBase();
      } else {
        setBase((com.cutejiuge.base.Base)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EMAIL:
      return getEmail();

    case NICK_NAME:
      return getNickName();

    case PASSWORD:
      return getPassword();

    case IMG_CHECK_CODE:
      return getImgCheckCode();

    case EMAIL_VERIFY_CODE:
      return getEmailVerifyCode();

    case BASE:
      return getBase();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EMAIL:
      return isSetEmail();
    case NICK_NAME:
      return isSetNickName();
    case PASSWORD:
      return isSetPassword();
    case IMG_CHECK_CODE:
      return isSetImgCheckCode();
    case EMAIL_VERIFY_CODE:
      return isSetEmailVerifyCode();
    case BASE:
      return isSetBase();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof UserRegisterRequest)
      return this.equals((UserRegisterRequest)that);
    return false;
  }

  public boolean equals(UserRegisterRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_email = true && this.isSetEmail();
    boolean that_present_email = true && that.isSetEmail();
    if (this_present_email || that_present_email) {
      if (!(this_present_email && that_present_email))
        return false;
      if (!this.email.equals(that.email))
        return false;
    }

    boolean this_present_nickName = true && this.isSetNickName();
    boolean that_present_nickName = true && that.isSetNickName();
    if (this_present_nickName || that_present_nickName) {
      if (!(this_present_nickName && that_present_nickName))
        return false;
      if (!this.nickName.equals(that.nickName))
        return false;
    }

    boolean this_present_password = true && this.isSetPassword();
    boolean that_present_password = true && that.isSetPassword();
    if (this_present_password || that_present_password) {
      if (!(this_present_password && that_present_password))
        return false;
      if (!this.password.equals(that.password))
        return false;
    }

    boolean this_present_imgCheckCode = true && this.isSetImgCheckCode();
    boolean that_present_imgCheckCode = true && that.isSetImgCheckCode();
    if (this_present_imgCheckCode || that_present_imgCheckCode) {
      if (!(this_present_imgCheckCode && that_present_imgCheckCode))
        return false;
      if (!this.imgCheckCode.equals(that.imgCheckCode))
        return false;
    }

    boolean this_present_emailVerifyCode = true;
    boolean that_present_emailVerifyCode = true;
    if (this_present_emailVerifyCode || that_present_emailVerifyCode) {
      if (!(this_present_emailVerifyCode && that_present_emailVerifyCode))
        return false;
      if (this.emailVerifyCode != that.emailVerifyCode)
        return false;
    }

    boolean this_present_base = true && this.isSetBase();
    boolean that_present_base = true && that.isSetBase();
    if (this_present_base || that_present_base) {
      if (!(this_present_base && that_present_base))
        return false;
      if (!this.base.equals(that.base))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEmail()) ? 131071 : 524287);
    if (isSetEmail())
      hashCode = hashCode * 8191 + email.hashCode();

    hashCode = hashCode * 8191 + ((isSetNickName()) ? 131071 : 524287);
    if (isSetNickName())
      hashCode = hashCode * 8191 + nickName.hashCode();

    hashCode = hashCode * 8191 + ((isSetPassword()) ? 131071 : 524287);
    if (isSetPassword())
      hashCode = hashCode * 8191 + password.hashCode();

    hashCode = hashCode * 8191 + ((isSetImgCheckCode()) ? 131071 : 524287);
    if (isSetImgCheckCode())
      hashCode = hashCode * 8191 + imgCheckCode.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(emailVerifyCode);

    hashCode = hashCode * 8191 + ((isSetBase()) ? 131071 : 524287);
    if (isSetBase())
      hashCode = hashCode * 8191 + base.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(UserRegisterRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetEmail(), other.isSetEmail());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmail()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.email, other.email);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNickName(), other.isSetNickName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNickName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nickName, other.nickName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPassword(), other.isSetPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.password, other.password);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetImgCheckCode(), other.isSetImgCheckCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImgCheckCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imgCheckCode, other.imgCheckCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEmailVerifyCode(), other.isSetEmailVerifyCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmailVerifyCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emailVerifyCode, other.emailVerifyCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBase(), other.isSetBase());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBase()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.base, other.base);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("UserRegisterRequest(");
    boolean first = true;

    sb.append("email:");
    if (this.email == null) {
      sb.append("null");
    } else {
      sb.append(this.email);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nickName:");
    if (this.nickName == null) {
      sb.append("null");
    } else {
      sb.append(this.nickName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("password:");
    if (this.password == null) {
      sb.append("null");
    } else {
      sb.append(this.password);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("imgCheckCode:");
    if (this.imgCheckCode == null) {
      sb.append("null");
    } else {
      sb.append(this.imgCheckCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("emailVerifyCode:");
    sb.append(this.emailVerifyCode);
    first = false;
    if (isSetBase()) {
      if (!first) sb.append(", ");
      sb.append("base:");
      if (this.base == null) {
        sb.append("null");
      } else {
        sb.append(this.base);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (base != null) {
      base.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserRegisterRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UserRegisterRequestStandardScheme getScheme() {
      return new UserRegisterRequestStandardScheme();
    }
  }

  private static class UserRegisterRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<UserRegisterRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, UserRegisterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EMAIL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.email = iprot.readString();
              struct.setEmailIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NICK_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nickName = iprot.readString();
              struct.setNickNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.password = iprot.readString();
              struct.setPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IMG_CHECK_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imgCheckCode = iprot.readString();
              struct.setImgCheckCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EMAIL_VERIFY_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.emailVerifyCode = iprot.readI64();
              struct.setEmailVerifyCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 255: // BASE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.base = new com.cutejiuge.base.Base();
              struct.base.read(iprot);
              struct.setBaseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, UserRegisterRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.email != null) {
        oprot.writeFieldBegin(EMAIL_FIELD_DESC);
        oprot.writeString(struct.email);
        oprot.writeFieldEnd();
      }
      if (struct.nickName != null) {
        oprot.writeFieldBegin(NICK_NAME_FIELD_DESC);
        oprot.writeString(struct.nickName);
        oprot.writeFieldEnd();
      }
      if (struct.password != null) {
        oprot.writeFieldBegin(PASSWORD_FIELD_DESC);
        oprot.writeString(struct.password);
        oprot.writeFieldEnd();
      }
      if (struct.imgCheckCode != null) {
        oprot.writeFieldBegin(IMG_CHECK_CODE_FIELD_DESC);
        oprot.writeString(struct.imgCheckCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(EMAIL_VERIFY_CODE_FIELD_DESC);
      oprot.writeI64(struct.emailVerifyCode);
      oprot.writeFieldEnd();
      if (struct.base != null) {
        if (struct.isSetBase()) {
          oprot.writeFieldBegin(BASE_FIELD_DESC);
          struct.base.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserRegisterRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UserRegisterRequestTupleScheme getScheme() {
      return new UserRegisterRequestTupleScheme();
    }
  }

  private static class UserRegisterRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<UserRegisterRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserRegisterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetEmail()) {
        optionals.set(0);
      }
      if (struct.isSetNickName()) {
        optionals.set(1);
      }
      if (struct.isSetPassword()) {
        optionals.set(2);
      }
      if (struct.isSetImgCheckCode()) {
        optionals.set(3);
      }
      if (struct.isSetEmailVerifyCode()) {
        optionals.set(4);
      }
      if (struct.isSetBase()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetEmail()) {
        oprot.writeString(struct.email);
      }
      if (struct.isSetNickName()) {
        oprot.writeString(struct.nickName);
      }
      if (struct.isSetPassword()) {
        oprot.writeString(struct.password);
      }
      if (struct.isSetImgCheckCode()) {
        oprot.writeString(struct.imgCheckCode);
      }
      if (struct.isSetEmailVerifyCode()) {
        oprot.writeI64(struct.emailVerifyCode);
      }
      if (struct.isSetBase()) {
        struct.base.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserRegisterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.email = iprot.readString();
        struct.setEmailIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nickName = iprot.readString();
        struct.setNickNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.password = iprot.readString();
        struct.setPasswordIsSet(true);
      }
      if (incoming.get(3)) {
        struct.imgCheckCode = iprot.readString();
        struct.setImgCheckCodeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.emailVerifyCode = iprot.readI64();
        struct.setEmailVerifyCodeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.base = new com.cutejiuge.base.Base();
        struct.base.read(iprot);
        struct.setBaseIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

