spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  type-aliases-package: com.easy_pan.back
  mapper-locations: classpath*:/mapper/**/*.xml